### ISSUE TITLE
Branch Protection

### ISSUE THREAD

**Issue by ethan-w-foshee** [ethan-w-foshee/TerraStella#10]
Could we (you) work on a Branch Ruleset? Just so we don't need to worry about accidental merges?

**Comment by CyborgPotato** [comment]
I don't seem to have permissions to do so @ethan-w-foshee

**Comment by ethan-w-foshee** [comment]
Ah shoot. Okay. Then I'll take a look into it, but would like your guidance on it.

**Comment by ethan-w-foshee** [comment]
I DID get a ruleset setup, but when we're both around, I'm gonna have you look over it. @CyborgPotato
