### ISSUE TITLE
Configure GitHub Pages

### ISSUE THREAD

**Issue by CyborgPotato** [ethan-w-foshee/TerraStella#4]
@ethan-w-foshee we need to configure github pages (if not just for the app itself, but also we can use it for the flowchart w/ [mermaid js](https://mermaid.js.org/))

**Comment by ethan-w-foshee** [comment]
I was thinking we could just use GitHub pages for the main application.
[This has been my reference so far](https://github.com/pmotschmann/Evolve)
He does have a wiki hosted from the same GitHub pages, so I bet he also has some other pages for things.

My one worry is if we host the flowchart in this same repo, people could find it with ease. If that's okay with you, it's also okay with me.

**Comment by CyborgPotato** [comment]
@ethan-w-foshee that's what I was hoping for is to use GitHub Pages for the main application, just like the evolve does

As for the flowchart I'm thinking it would be good for that to be hidden, yes, so either we can work on it in private, or we can use some kind of secret management like [sops](https://github.com/getsops/sops) so that it's not only hidden but also able to be version controlled for us

**Comment by ethan-w-foshee** [comment]
For now, I'm not worried about keeping things hidden. Is it something easier to add later on @CyborgPotato ?

**Comment by CyborgPotato** [comment]
We can hide later on p easily @ethan-w-foshee

**Comment by ethan-w-foshee** [comment]
Then I can hop on configuring GitHub pages pretty easily. I'm thinking we might have a deployment branch, different from our main branch?

**Comment by CyborgPotato** [comment]
Either or works, something separate would be good

**Comment by ethan-w-foshee** [comment]
I have created the branch "deploy" and had GH-Pages deploy it already. I was thinking that we *might* want to rework file structure for a bit of organization? But GH-Pages is deploying already at https://ethan-w-foshee.github.io/TerraStella/

You can close this if you aren't worried about the file structure, or keep it open and comment if you have an idea for file structure
